Planner/Entities/EFContext.cs
using Planner.Entities.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Planner.Entities
{
    public class EFContext: DbContext
    {
        public DbSet<Plan> Plans { get; set; }
    }
}

Planner/Entities/Initializers/EntityInitializer.cs
using Planner.Entities.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Planner.Entities.Initializers
{
    public class EntityInitializer : DropCreateDatabaseIfModelChanges<EFContext>
    {
        protected override void Seed(EFContext context)
        {
            context.Plans.Add(new Plan 
            { 
                Title = "Make a project",
                Description = "Project for art lesson",
                Date = DateTime.Now.Date,
                IsPriority = false,
                Image = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/758px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg" });
            base.Seed(context);
        }
    }
}

Planner/Entities/Models/Plan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Planner.Entities.Models
{
    public class Plan
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public bool IsPriority { get; set; }
        public string Image { get; set; }
    }
}

Planner/Models/AddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Planner.Models
{
    public class AddViewModel
    {
        [Required(ErrorMessage = "Title is required")]
        [Display(Name = "Title: ")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Description is required")]
        [Display(Name = "Description: ")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Date is required")]
        [Display(Name = "Date: ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }
        [Required]
        public bool IsPriority { get; set; }
        public string Image { get; set; }
    }
}

Planner/Models/PlanViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Planner.Models
{
    public class PlanViewModel
    {
        [Required]
        public int Id { get; set; }
        [Required(ErrorMessage = "Title is required")]
        [Display(Name = "Title: ")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Description is required")]
        [Display(Name = "Description: ")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Date is required")]
        [Display(Name = "Date: ")]
        public DateTime Date { get; set; }
        [Required]
        public bool IsPriority { get; set; }
        public string Image { get; set; }
    }
}

Planner/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Planner.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Planner/Controllers/PlansController.cs
using Planner.Entities;
using Planner.Entities.Models;
using Planner.Helpers;
using Planner.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Planner.Controllers
{
    public class PlansController : Controller
    {
        private readonly EFContext _context;
        public PlansController()
        {
            _context = new EFContext();
        }
        // GET: Plans
        public ActionResult ListPlans()
        {
            IEnumerable<PlanViewModel> models = _context.Plans.Select(m => new PlanViewModel
            {
                Id = m.Id,
                Title = m.Title,
                Description = m.Description,
                Image = m.Image,
                Date = m.Date,
                IsPriority = m.IsPriority
            });
            return View(models);
        }

        public ActionResult Calendar(DateTime date)
        {
            var model = _context.Plans.Where(x => x.Date == date).Select(n => new PlanViewModel
            {
                Date = n.Date,
                Description = n.Description,
                Id = n.Id,
                Image = n.Image,
                IsPriority = n.IsPriority,
                Title = n.Title
            });
            return PartialView(model);
        }


        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(AddViewModel model, HttpPostedFileBase imageFile)
        {
            string fileName = Guid.NewGuid().ToString() + ".jpg";
            string image = Server.MapPath(Constants.ImagePath) + "\\" + fileName;
            using (Bitmap bmp = new Bitmap(imageFile.InputStream))
            {
                Bitmap saveImage = ImageWorker.CreateImage(bmp, 400, 400);
                if(saveImage!=null)
                {
                    saveImage.Save(image);
                    Plan plan = new Plan
                    {
                        Title = model.Title,
                        Description = model.Description,
                        Date = model.Date,
                        Image = fileName,
                        IsPriority = false
                    };
                    _context.Plans.Add(plan);
                    _context.SaveChanges();
                }
               
            }
            return RedirectToAction("ListPlans");
        }

        public ActionResult Delete(int id)
        {
            _context.Plans.Remove(_context.Plans.Find(id));
            _context.SaveChanges();
            return RedirectToAction("ListPlans");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Plan plan = _context.Plans.Find(id);
            PlanViewModel model = new PlanViewModel
            {
                Id = plan.Id,
                Date = plan.Date,
                Description = plan.Description,
                Image = plan.Image,
                IsPriority = plan.IsPriority,
                Title = plan.Title
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(PlanViewModel model)
        {
            Plan plan = _context.Plans.Find(model.Id);
            plan.Title = model.Title;
            plan.Image = model.Image;
            plan.IsPriority = model.IsPriority;
            plan.Date = model.Date;
            plan.Description = model.Description;
            _context.SaveChanges();
            return RedirectToAction("ListPlans");
        }

        public ActionResult Sort(string sort, int? order)
        {
            IEnumerable<PlanViewModel> model = _context.Plans.Select(m => new PlanViewModel()
            {
                Id = m.Id,
                Title = m.Title,
                Description = m.Description,
                Image = m.Image,
                Date = m.Date,
                IsPriority = m.IsPriority
            });
            switch (sort)
            {
                case "title":
                    {
                        model = model.OrderBy(ord => ord.Title);
                        break;
                    }
            }
            return View("ListPlans", model);
        }

    }
}

Planner/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Planner/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Planner/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Planner/Views/Plans/Create.cshtml
@model Planner.Models.AddViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Plans", FormMethod.Post, new { enctype = "multipart/form-data" } ))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AddViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPriority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPriority)
                    @Html.ValidationMessageFor(model => model.IsPriority, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imageFile"/>
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Planner/Views/Plans/Edit.cshtml
@model Planner.Models.PlanViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PlanViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPriority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPriority)
                    @Html.ValidationMessageFor(model => model.IsPriority, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Planner/Views/Plans/ListPlans.cshtml
@model IEnumerable<Planner.Models.PlanViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>ListPlans</h2>


@using (Html.BeginForm("Calendar", "Plans", FormMethod.Get, new { id = "dateForm" }))
{
    @Html.TextBox("date", null, new { type = "date", id = "mydate" })
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
            <a href="/Plans/Sort/?sort=title" class="glyphicon glyphicon-chevron-down title"></a>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPriority)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>

            @if ((item.Date - DateTime.Now).TotalDays <= 1)
            {
                <td style="background: red">
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
            }
            else
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
            }

            <td>
                @Html.EditorFor(modelItem => item.IsPriority)
            </td>
            <td>
                <img style="height: 50px" src="~/Images/@item.Image">
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<script>
    onload = () => {
        document.getElementById("item_IsPriority").onchange = () => {
            alert("hello")
        }
        document.getElementById("mydate").onchange = () => {
            document.getElementById("dateForm").submit();
        }
    }

</script>

Planner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("My Plans", "ListPlans", "Plans")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>